#ifndef __GODDESSANAMACROSINCLUDES__
#define __GODDESSANAMACROSINCLUDES__

#include <iostream>
#include <fstream>
#include <sstream>
#include <streambuf>
#include <string>
#include <vector>
#include <map>
#include <random>
#include <type_traits>
#include <cxxabi.h>
#include <pthread.h>
#include <dirent.h>
#include <utility>
#include <tuple>
#include <array>
#include <chrono>
#include <ctime>
#include <math.h>

#include "TROOT.h"
#include "TSystem.h"
#include <TQObject.h>
#include "TObject.h"
#include "TBrowser.h"
#include "TCanvas.h"
#include "TString.h"
#include "TDialogCanvas.h"
#include "TFrame.h"
#include "TList.h"
#include "TLine.h"
#include "TGraph.h"
#include "TTree.h"
#include "TChain.h"
#include "TBranch.h"
#include "TH2F.h"
#include "TFile.h"
#include "TH1F.h"
#include "TH1D.h"
#include "TMath.h"
#include "TF1.h"
#include "TDirectoryFile.h"
#include "TFitResult.h"
#include "TFitResultPtr.h"
#include "TButton.h"
#include "TStyle.h"
#include "TMarker.h"

#include <TApplication.h>
#include <TVirtualX.h>
#include <TGClient.h>
#include <THashList.h>
#include <TCanvas.h>
#include <TF1.h>
#include <TRandom.h>
#include <TGWindow.h>
#include <TGButton.h>
#include <TGFrame.h>
#include <TGLabel.h>
#include <TGLayout.h>
#include <TGDimension.h>
#include <TGText.h>
#include <TGTextEntry.h>
#include <TGNumberEntry.h>
#include <TRootEmbeddedCanvas.h>
#include <RQ_OBJECT.h>

#include "SolidVector.h"
#include "GoddessStruct.h"

using std::map;
using std::string;
using std::vector;
using std::cout;
using std::cerr;
using std::clog;
using std::endl;

#endif